### ISSUE TITLE
error CS0103: The name 'IAPWrapper' does not exist in the current context

### ISSUE THREAD

**Issue by Thaina** [facebook/facebook-sdk-for-unity#755]
## Checklist

- [ x ] I've updated to the latest released version of the SDK
- [ x ] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [ x ] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [ x ] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [ x ] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: `2022.3.12f`
- Unity SDK Version: `18.0.0`
- Installation Platform & Verison: `Android` version `X.X.X`

## Goals

Import FBSDK 18.0

## Expected Results

No Error

## Actual Results

Assets\FacebookSDK\Examples\Mobile\Scripts\SubMenus\IAP.cs(72,17): error CS0103: The name 'IAPWrapper' does not exist in the current context

## Steps to Reproduce

Just import FBSDK into unity 2022.3.12f

## Code Samples & Details

Just import FBSDK into unity 2022.3.12f

![Image](https://github.com/user-attachments/assets/f3ff5a3d-8013-4d26-9b65-23d8982be97a)

**Comment by CodezTree** [comment]
Same problem here.

FB unity SDK 18.0.0
Unity version 6000.0.47f1
iOS

**Comment by maaz-msf** [comment]
> Same problem here.
> 
> FB unity SDK 18.0.0 Unity version 6000.0.47f1 iOS
> 
> edit : for someone who using Unity 6 -> It works with 17.0.1 version.
> 
> * iOS build should have to setup some postprocess script

didnt worked for me

**Comment by CodezTree** [comment]
They finally fixed this problem on commit dec9a25 !! 🥺

> > Same problem here.
> > FB unity SDK 18.0.0 Unity version 6000.0.47f1 iOS
> > edit : for someone who using Unity 6 -> It works with 17.0.1 version.
> > 
> > * iOS build should have to setup some postprocess script
> 
> didnt worked for me

17.0.1 Example doesn't have IAP.cs file (also IAPWrapper.cs) in example folder, so it should work. Try remove whole Facebook folder inside Asset folder and reimport it (17.0.1). I think previous file that wasn't remove still bothering you.
