### ISSUE TITLE
Undefined symbols for architecture armv7

### ISSUE THREAD

**Issue by jbourne23** [facebook/facebook-sdk-for-unity#272]
I have Facebook with Firebase and I receive this error when update from Facebook v7.15.1 to v7.16.x or v7.17.x (in Xcode, iOS platform):

> Undefined symbols for architecture armv7:
>   "_OBJC_CLASS_$_FIRDynamicLinks", referenced from:
>       objc-class-ref in libFirebaseCppApp.a(invites_receiver_internal_ios_fe43142c9b5429d3e0c956b7297ce932.o)
> ld: symbol(s) not found for architecture armv7

It refers to Firebase, but happen when I update Facebook. If I am receiving the error and I change Facebook to v7.15.1 again, it works fine as usual.

Does anyone have an idea of what may be happening? Thanks in advance.

**Comment by daCelky** [comment]
Same problem here, since 7.15.1 there is no stable version of Facebook SDK I assume :/

**Comment by matthewwwillard** [comment]
Having same issues

**Comment by Chang10412** [comment]
I add this line "<iosPod name="Firebase/DynamicLinks"/>" to the file "Unity/Assets/FacebookSDK/Plugins/Editor/Dependencies.xml",
and project is successfully compiled.
Maybe the latest sdk is dependent upon firebase dynamiclinks library.

**Comment by matthewwwillard** [comment]
Was able to get it working by updating to 17.7.1 and combining @Chang10412 fix with another.
`<iosPods>
        
        <iosPod name="Firebase/DynamicLinks" />
        <iosPod name="FBSDKCoreKit" version="~> 5.2" />
        <iosPod name="FBSDKLoginKit" version="~> 5.2" />
        <iosPod name="FBSDKShareKit" version="~> 5.2" />
    </iosPods>`

**Comment by jbourne23** [comment]
> I add this line "iosPod name="Firebase/DynamicLinks"" to the file "Unity/Assets/FacebookSDK/Plugins/Editor/Dependencies.xml",
> and project is successfully compiled.
> Maybe the latest sdk is dependent upon firebase dynamiclinks library.

It works, thanks!
