### ISSUE TITLE
Facebook SDK (v14.0.0) iOS Archive Failure - IPA Processing Failed w/ CocoaPods v1.11

### ISSUE THREAD

**Issue by cdedear-sg** [facebook/facebook-sdk-for-unity#631]
## Checklist

- [Y] I've updated to the latest released version of the SDK
- [Y] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-sdk-for-unity/issues)
- [Y] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [Y] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [Y] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment

Describe your dev environment here, giving as many details as possible. If you have them, make sure to include:

- Unity Editor Version: 2020.3.26f1
- Facebook SDK Version: 14.0.0
- Installation Platform: iOS
- Target Version: v11.0
- XCode – v13.4.1
- Cocoapods – v1.11.0+

## Goals

**What do you want to achieve?**
I am attempting to create an iOS build with Facebook SDK (v14.0.0).

## Expected Results

**What do you expect to happen?**
.ipa is generated and I can install it on my device

## Actual Results

**What actually happened?**
I receive an "IPA processing failed" error message during the bitcode compile portion of the distribution process. 

## Steps to Reproduce

What are the steps necessary to reproduce this issue?

- Get XCode v13.4.1
- Install/Set CocoaPods to version 1.11.0 (or higher)
- Create a new Unity Project (v2020.3.26f1)
  - Switch Build Settings to iOS platform
  - Setup provisioning details in player settings
  - Import the Facebook SDK (v14.0.0) package
  - Follow the FAQ Troubleshooting unity SDK 14.0.0 steps (https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0)
  - Create a build
    - Run in Xcode: v13.4.1
    - Run in Xcode as: Debug
- In XCode
  - Platform > Build
  - Platform > Archive
  - Archives Window > Distribute App
    - Development
      - App Thinning: None
      - Select _Rebuild from Bitcode_
      - Select _Strip Swift symbols_
      - Automatically manage signing

At this point, I would hit the IPA processing failed error.

## Code Samples & Details

I am attempting to create an iOS build with the Facebook SDK (v14.0.0) in an empty project. While the build will complete successfully, when trying to archive and distribute, I am running into an error: **IPA processing failed**. 

This error seems to occur when my CocoaPods is at a version of 1.11+. If I downgrade my CocoaPods to 1.10.2, then the builds will make it through the archival/distribution process and I can get the .ipa. However, our build process uses CocoaPods v1.11 and I will not be able to downgrade that.

Looking at the IDEDistributionPipeline.log I see the following error:

```
Step "<IDEDistributionCompileBitcodeStep: 0x7fb346488060>" failed with error "Error Domain=IDEFoundationErrorDomain Code=1 "IPA processing failed" UserInfo={NSLocalizedDescription=IPA processing failed}"
```

In that same file, the only assertion I am seeing is:
```
Assertion failed: Duplicate symbols for 3086ED84-3D1C-392E-A044-174FD373ACA2
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:619:in `addSymbols'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2919:in `block in CompileOrStripBitcodeInBundle'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2828:in `each'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:2828:in `CompileOrStripBitcodeInBundle'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:3115:in `block in ProcessIPA'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:3076:in `each'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:3076:in `ProcessIPA'
/Applications/Xcode.app/Contents/Developer/usr/bin/ipatool:4038:in `<main>'
```

The other logs do not appear to have any errors or assertions. 

I have followed all the steps listed here: 
https://github.com/facebook/facebook-sdk-for-unity/wiki/FAQ---Troubleshooting-Unity-SDK-14.0.0

**Comment by lebasp** [comment]
Hi we are having the same issue since the mid year, we tried Unity 2021.3.x and XCodes (13.3.x, 13.4.x, 14.x)
also we are having this issue in Unity Facebook SDKs 11+

We downgraded the cocoapods to 1.10.2 and it didn't fix the issue on our local machine.
on Unity 2020 with XCode 13.2.x or less it was working properly.

**Comment by JordiFB** [comment]
Could you try to use the latest version of Facebook Unity SDK 15.1.0 with cocoapods version 1.11.3 ? Thank you so much.

**Comment by jtigner-sg** [comment]
@JordiFB - Unfortunately, we are unable to upgrade to the Facebook Unity 15.1.0 SDK due to the iOS portion dropping support for iOS 11, setting the minimum version to 12.0.
Unity 2020 and 2021, which are still in LTS support support iOS 11 and this is a non-trivial amount of revenue for us.

**Comment by JordiFB** [comment]
@jtigner-sg  Could you try to disable Bitcode in the final Xcode project?

Basically set  Build Settings > Enable Bitcode  param to NO  in the project and all targets. 

The new sdk version disable this field automatically but you can do it manually.
