### ISSUE TITLE
Crash at startup on iOS 7 devices. Symbol not found: _OBJC_CLASS_$_UIAlertAction

### ISSUE THREAD

**Issue by mhalttu** [facebook/facebook-sdk-for-unity#123]
After updating out SDK to 7.10.0 our game has started to crash on iOS 7.x devices. The problem exists in 7.10.1 too.

The error is "dyld: Symbol not found: _OBJC_CLASS_$_UIAlertAction" and reverting back to 7.9.0 fixes the crash.

**Comment by mhalttu** [comment]
In https://developers.facebook.com/docs/ios/change-log-4x/ I see the following change "Replace deprecated UIActionSheet with UIAlertController" which could be related. I couldn't find any information what is the minimum supported version of Facebook SDK for iOS.

**Comment by niezbop** [comment]
Hey! I have faced similar issues while trying to get our game running on iOS 7.x. The issue is that the facebook Unity SDK relies on the facebook SDK post 4.15 which dropped iOS7 support... https://developers.facebook.com/bugs/293861737725077/

> Günay Mert Karadogan
> Hi Jason,
> 
> It turns out that iOS SDK dropped iOS 7 support when Xcode 8 dropped it (as we usually only support the latest Xcode). It isn't supported since v4.15.1.
> 
> All the best,
> Günay

Which should be mentioned somewhere I guess. The last Facebook SDK version which still builds for iOS 7  is the 7.8.0. Sadly there are some slight issues with Unity 5.6.

Best of luck with your project,
Paul
