### ISSUE TITLE
Game crash after start on iOS with fbsdk v16

### ISSUE THREAD

**Issue by uchar** [facebook/facebook-sdk-for-unity#694]
This is related to https://github.com/facebook/facebook-sdk-for-unity/issues/659 
I'm creating this issue because it seems that no one cares about an issue that crashes all iOS builds!!!
I don't understand how you guys didn't fix this issue from "Dec 12, 2022" !! We just wasted 3 days on this! 
I mean did you even build a project "once" before release !!!?

**Comment by vg-swift** [comment]
https://github.com/facebook/facebook-sdk-for-unity/issues/688

**Comment by uchar** [comment]
dead plugin

**Comment by vg-swift** [comment]
> dead plugin

What do you mean? I describe the solution in the thread I posted

**Comment by uchar** [comment]
> > dead plugin
> 
> What do you mean? I describe the solution in the thread I posted

unchecking that doesn't work in our projects , Firebase and some of google plugins will give build errors

**Comment by vg-swift** [comment]
> unchecking that doesn't work in our projects , Firebase and some of google plugins will throw build errors

We also use Firebase and google plugins. What about all the other parts I mentioned, what's your cocoapods version and xcode version?

**Comment by uchar** [comment]
> 

cocoapods is 1.12.1 and xcode 14.3.1

**Comment by uchar** [comment]
> > unchecking that doesn't work in our projects , Firebase and some of google plugins will throw build errors
> 
> We also use Firebase and google plugins. What about all the other parts I mentioned, what's your cocoapods version and xcode version?


cocoapods is 1.12.1 and xcode 14.3.1

**Comment by uchar** [comment]
> > unchecking that doesn't work in our projects , Firebase and some of google plugins will throw build errors
> 
> We also use Firebase and google plugins. What about all the other parts I mentioned, what's your cocoapods version and xcode version?

Error is : 
``` 
Undefined symbols for architecture arm64:

  "_GADAdLoaderAdTypeNative", referenced from:

      ___73-[ALGoogleMediationAdapter loadAdViewAdForParameters:adFormat:andNotify:]_block_invoke in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

      ___64-[ALGoogleMediationAdapter loadNativeAdForParameters:andNotify:]_block_invoke in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_GADAdSizeBanner", referenced from:

      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_GADAdSizeLeaderboard", referenced from:

      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_GADAdSizeMediumRectangle", referenced from:

      -[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:] in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth", referenced from:

      ___75-[ALGoogleMediationAdapter adSizeFromAdFormat:isAdaptiveBanner:parameters:]_block_invoke in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

      +[ALGoogleMediationAdapter currentOrientationAchoredAdaptiveBannerSizeWithWidth:] in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_GADGetStringFromVersionNumber", referenced from:

      -[ALGoogleMediationAdapter SDKVersion] in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_OBJC_CLASS_$_GADAdLoader", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_OBJC_CLASS_$_GADAppOpenAd", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_OBJC_CLASS_$_GADBannerView", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_OBJC_CLASS_$_GADExtras", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

     (maybe you meant: _OBJC_CLASS_$_GADExtrasBridge)

  "_OBJC_CLASS_$_GADInterstitialAd", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

     (maybe you meant: _OBJC_CLASS_$_GADInterstitialAdBridgeV8)

  "_OBJC_CLASS_$_GADMediaView", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleNativeAdDelegate.o)

      objc-class-ref in libGoogleAdapter.a(ALGoogleNativeAd.o)

      objc-class-ref in libGoogleAdapter.a(ALGoogleNativeAdViewDelegate.o)

  "_OBJC_CLASS_$_GADMobileAds", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

     (maybe you meant: _OBJC_CLASS_$_GADMobileAdsBridge)

  "_OBJC_CLASS_$_GADNativeAdImageAdLoaderOptions", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_OBJC_CLASS_$_GADNativeAdView", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleNativeAd.o)

      objc-class-ref in libGoogleAdapter.a(ALGoogleNativeAdViewDelegate.o)

  "_OBJC_CLASS_$_GADNativeAdViewAdOptions", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

  "_OBJC_CLASS_$_GADQueryInfo", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

     (maybe you meant: _OBJC_CLASS_$_GADQueryInfoBridge)

  "_OBJC_CLASS_$_GADRequest", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

     (maybe you meant: _OBJC_CLASS_$_GADRequestBridge, _OBJC_CLASS_$_GADRequestBridgeV85 )

  "_OBJC_CLASS_$_GADRewardedAd", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

     (maybe you meant: _OBJC_CLASS_$_GADRewardedAdBridge, _OBJC_CLASS_$_GADRewardedAdBridgeV8 )

  "_OBJC_CLASS_$_GADRewardedInterstitialAd", referenced from:

      objc-class-ref in libGoogleAdapter.a(ALGoogleMediationAdapter.o)

ld: symbol(s) not found for architecture arm64

clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by revolt3r** [comment]
We also use AppLoving with GoogleMediation Adapter, did you try updating the adapter?

**Comment by vg-swift** [comment]
We also use AppLovin with GoogleMediation Adapter, did you try updating the adapter?

**Comment by uchar** [comment]
It also seems to be related to this one https://github.com/googleads/googleads-mobile-unity/issues/2736
Because some people are having exactly same error , seems they fixed it 5days ago but It still not working here

**Comment by vg-swift** [comment]
Good to know, will avoid updating any ad adapters for now :)

**Comment by uchar** [comment]
Sadistic plugin, last week I tested all combinations of external dependency manager and all other settings possible and none worked!
I finally fixed it by downgrading Facebook SDK from 16.1 to 14.1.1 !

**Comment by abogarsukov-braingames** [comment]
We've the same issue after upgrading Facebook from 14 to 16, but it our case it cannot load `DTBiOSSDK`.

**Comment by santiagomartinJC** [comment]
I could fix this by adding the addToAllTargets parameter in dependecies.xml
./Assets/FacebookSDK/Plugins/Editor/Dependencies.xml
```

    <iosPods>
        <iosPod name="FBSDKCoreKit_Basics" version="~> 15.1" **addToAllTargets="true"** />
        <iosPod name="FBSDKCoreKit" version="~> 15.1" **addToAllTargets="true"**/>
        <iosPod name="FBSDKLoginKit" version="~> 15.1" **addToAllTargets="true"**/>
        <iosPod name="FBSDKShareKit" version="~> 15.1" **addToAllTargets="true"**/>
        <iosPod name="FBSDKGamingServicesKit" version="~> 15.1" **addToAllTargets="true"**/>
    </iosPods>
```
https://github.com/facebook/facebook-sdk-for-unity/issues/659#issuecomment-1643864386

**Comment by NudeNULL** [comment]
In my case it was crashing because of the DisableBitcode script, since I deleted it the app started

**Comment by NudeNULL** [comment]
Actually no, it didn't help, no idea what happened then...But without Facebook SDK, even with 5-6 other SDKs everything works well, as always, gotta love the SDK team from facebook

**Comment by fblostoke** [comment]
@uchar Feeling your pain m8! This is riddiculous that integrating simple stuff like an SDK takes days of work.

I think I got te working combination of setting to build iOS without crashing for FBSdk 16.0.1, Firebase 10.7.0 and AppLovinSDK 11.11.3:

Contrary to AppLovin docs, I checked all the toggles in the iOS Resolver Settings:
![Screenshot 2023-10-12 at 11 05 33](https://github.com/facebook/facebook-sdk-for-unity/assets/102795105/546dfc9b-2770-4f28-8839-7a1f7cb92b66)

My Podfile looks like this (last part added during build callback):
![Screenshot 2023-10-12 at 11 06 15](https://github.com/facebook/facebook-sdk-for-unity/assets/102795105/5678e194-3ecc-4190-8549-639df65d6677)

Build Postprocess callback looks like this:
![Screenshot 2023-10-12 at 11 09 40](https://github.com/facebook/facebook-sdk-for-unity/assets/102795105/b9334c08-85f6-4a05-b664-7056259df0ee)

Hope this helps!

**Comment by Aare-** [comment]
@uchar Feeling your pain m8! This is riddiculous that integrating simple stuff like an SDK takes days of work.

I think I got te working combination of setting to build iOS without crashing for FBSdk 16.0.1, Firebase 10.7.0 and AppLovinSDK 11.11.3:

Contrary to AppLovin docs, I checked all the toggles in the iOS Resolver Settings:
![274545451-546dfc9b-2770-4f28-8839-7a1f7cb92b66](https://github.com/facebook/facebook-sdk-for-unity/assets/2124653/a728e728-8d30-450e-b02e-a6b6d7965c24)

My Podfile looks like this (last part added during build callback):
![274545669-5678e194-3ecc-4190-8549-639df65d6677](https://github.com/facebook/facebook-sdk-for-unity/assets/2124653/f36d1eb1-393f-440c-b0dd-d9427b10b1cb)

Build Postprocess callback looks like this:
![274546721-b9334c08-85f6-4a05-b664-7056259df0ee](https://github.com/facebook/facebook-sdk-for-unity/assets/2124653/ed886719-dee6-4c2d-9521-3ea2876a3759)

I also have Dependencies.xml set up like in the comment above:
https://github.com/facebook/facebook-sdk-for-unity/issues/694#issuecomment-1728280614

Hope this helps!

**Comment by NudeNULL** [comment]
Hey @Aare-, thanks for sharing your experience with getting it to work, could you please send as plain text to copy it easier?
Thanks!

**Comment by NudeNULL** [comment]
On my side I get NULL Ref inside unitys methods at this line
string mainTarget = pbxProject.GetUnityMainTargetGuid();

Trying to find out another method of getting the target name...

**Comment by Aare-** [comment]
> On my side I get NULL Ref inside unitys methods at this line string mainTarget = pbxProject.GetUnityMainTargetGuid();
> 
> Trying to find out another method of getting the target name...

Sorry, mistake on my part - you should call pbxProject.ReadFromFile(projectPath); before trying to resolve targets.
Updated the original code

**Comment by NudeNULL** [comment]
Thanks for the update @Aare- , but I can't get the resulting podfile to look like yours, the bottom part is missing, no errors in logs, will try to investigate that for now.

**Comment by NudeNULL** [comment]
this is my podfile with the latest script changes used
`source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'AppLovinMediationAdColonyAdapter', '4.9.0.0.4'
  pod 'AppLovinMediationByteDanceAdapter', '5.4.1.1.0'
  pod 'AppLovinMediationFacebookAdapter', '6.14.0.0'
  pod 'AppLovinMediationFyberAdapter', '8.2.4.0'
  pod 'AppLovinMediationGoogleAdapter', '10.10.0.0'
  pod 'AppLovinMediationGoogleAdManagerAdapter', '10.10.0.0'
  pod 'AppLovinMediationInMobiAdapter', '10.5.8.1'
  pod 'AppLovinMediationIronSourceAdapter', '7.5.0.0.0'
  pod 'AppLovinMediationMintegralAdapter', '7.4.6.0.0'
  pod 'AppLovinMediationMyTargetAdapter', '5.19.0.0'
  pod 'AppLovinMediationSmaatoAdapter', '22.4.0.0'
  pod 'AppLovinMediationUnityAdsAdapter', '4.9.0.0'
  pod 'AppLovinMediationVungleAdapter', '7.1.0.0'
  pod 'AppLovinMediationYandexAdapter', '6.0.0.0'
  pod 'AppLovinSDK', '11.11.3'
  pod 'AppsFlyer-AdRevenue', '6.9.1'
  pod 'AppsFlyerFramework', '6.12.1'
  pod 'FBAudienceNetwork', '6.14.0.0'
  pod 'FBSDKCoreKit', '~> 15.1'
  pod 'FBSDKCoreKit_Basics', '~> 15.1'
  pod 'FBSDKGamingServicesKit', '~> 15.1'
  pod 'FBSDKLoginKit', '~> 15.1'
  pod 'FBSDKShareKit', '~> 15.1'
  pod 'Firebase/Analytics', '10.7.0'
  pod 'Firebase/Core', '10.7.0'
  pod 'YandexMobileMetrica', '4.2.0'
end
target 'Unity-iPhone' do
  pod 'FBSDKCoreKit', '~> 15.1'
  pod 'FBSDKCoreKit_Basics', '~> 15.1'
  pod 'FBSDKGamingServicesKit', '~> 15.1'
  pod 'FBSDKLoginKit', '~> 15.1'
  pod 'FBSDKShareKit', '~> 15.1'
end
use_frameworks! :linkage => :static
`

**Comment by NudeNULL** [comment]
Also I saw Facebook just released a newer version of SDK, even though the dependencies are still the same -> 16.0.1, I will try it anyway.

**Comment by NudeNULL** [comment]
No, it didn't help, will look into crash logs tomorrow

**Comment by NudeNULL** [comment]
Hey @Aare- , what version of Unity do you use?

**Comment by Aare-** [comment]
@NudeNULL I'm on 2021.3.23f

I'm not sure if the last part of the podfile is required, but you can always add it manually to the generated xcode project.
It should be added by the build post process script but depending on your other plugins it might get overwritten.

I also see you have a lot of other plugins added, it might be a good idea to add them one by one and check which one exactly is causing the problems.

**Comment by NudeNULL** [comment]
I am seeing a pattern where already two developers have their projects on 2021.3.xx and they dont have the crash, where mine project is on 2020 version, will try the update and write here the result

**Comment by uchar** [comment]
@NudeNULL Just use version 14 of facebook SDK, why do you want to update it ?  this version is broken and no one from the facebook team cares

**Comment by NudeNULL** [comment]
> @NudeNULL Just use version 14 of facebook SDK, why do you want to update it ?  this version is broken and no one from the facebook team cares
> About the Unity version, I had a crash on unity 2021.3 , it's not caused by unity

I am not sure what was the reason for the update, I tried so many things that I forgot about trying the downgrade for facebook SDK, will see what happens with newer version of unity and then will try.

Because after upgrading unity we now have an issue with certificates, have no idea what unity upgrade have to do with triggering an error that says that xcode can't find the certificate with private key for the team id, I am losing my mind and becoming an insane person, day by day, need some psychotherapy...
Thank you facebook sdk team for making me want to kill someone ....

**Comment by Aare-** [comment]
@NudeNULL Unrelated to this issue, but check out: https://docs.fastlane.tools/actions/match/
This solved my issues with certificates for good

**Comment by NudeNULL** [comment]
Finally got a working build.
The certificates issue was solved by removing the build step in our Jenkins job made by using Xcode plugin, and wrote a custom shell script (after a day of fighting with chatgpt), that builds ad hoc ipa file.

The Facebook crash was fixed by downgrading to 14.1 version.
