### ISSUE TITLE
17.8.0: java.lang.NoSuchMethodError: no static method with name='SetUserAgentSuffix' 

### ISSUE THREAD

**Issue by jackatfp** [facebook/facebook-sdk-for-unity#346]
- Unity Editor Version: 2019.2.9
- Installation Platform & Verison: Android
- Facebook Unity SDK Version: 17.8.0

We got a lot of crash report from Loggly since we upgraded to 17.8.0. We enable Proguard in the project and the setting is

-keep class com.facebook.internal.* {*;}

> {"VERSION":"1.3.5.0","LEVEL":"Exception","Message":"AndroidJavaException: java.lang.NoSuchMethodError: no static method with name='SetUserAgentSuffix' signature='(Ljava\/lang\/String;)V' in class Ljava.lang.Object;","Stack_Trace":"java.lang.NoSuchMethodError: no static method with name='SetUserAgentSuffix' signature='(Ljava\/lang\/String;)V' in class Ljava.lang.Object;\ncom.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:167)\ncom.unity3d.player.UnityPlayer.nativeRender(Native Method)\ncom.unity3d.player.UnityPlayer.c(Unknown Source:0)\ncom.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:78)\nandroid.os.Handler.dispatchMessage(Handler.java:104)\nandroid.os.Looper.loop(Looper.java:166)\ncom.unity3d.player.UnityPlayer$e.run(Unknown Source:20)\nUnityEngine.AndroidJNISafe.CheckException () (at <00000000000000000000000000000000>:0)\nUnityEngine.AndroidJNISafe.CallStaticObjectMethod (System.IntPtr clazz, System.IntPtr methodID, UnityEngine.jvalue[] args) (at <00000000000000000000000000000000>:0)\nUnityEngine.AndroidReflection.GetMethodMember (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <00000000000000000000000000000000>:0)\nUnityEngine._AndroidJNIHelper.GetMethodID (System.IntPtr jclass, System.String methodName, System.String signature, System.Boolean isStatic) (at <00000000000000000000000000000000>:0)\nUnityEngine.AndroidJavaObject._CallStatic (System.String methodName, System.Object[] args) (at <00000000000000000000000000000000>:0)\nFacebook.Unity.Mobile.Android.AndroidFacebook.Init (System.String appId, Facebook.Unity.HideUnityDelegate hideUnityDelegate, Facebook.Unity.InitDelegate onInitComplete) (at <00000000000000000000000000000000>:0)\nFacebook.Unity.FB+OnDLLLoaded.Invoke () (at <00000000000000000000000000000000>:0)\nFacebook.Unity.FB+CompiledFacebookLoader.Start () (at <00000000000000000000000000000000>:0)\n","Device_Model":"HUAWEI ANE-LX1"}

>

**Comment by KylinChang** [comment]
Hi @jackatfp , the function comes from [FB.java](https://github.com/facebook/facebook-sdk-for-unity/blob/master/facebook-android-wrapper/src/com/facebook/unity/FB.java) and you should add -keep class com.facebook.unity.* {*;} to your proguard.  Close the task now, feel free to reopen the issue if the problem still exists.
